In [4]:
import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()
%matplotlib inline

sess = tf.Session()

In [5]:
my_array = np.array([[1., 3., 5., 7., 9.],
                   [-2., 0., 2., 4., 6.],
                   [-6., -3., 0., 3., 6.]])
x_vals = np.array([my_array, my_array + 1])
print(x_vals)
x_data = tf.placeholder(tf.float32, shape=(3, 5))

[[[  1.   3.   5.   7.   9.]
  [ -2.   0.   2.   4.   6.]
  [ -6.  -3.   0.   3.   6.]]

 [[  2.   4.   6.   8.  10.]
  [ -1.   1.   3.   5.   7.]
  [ -5.  -2.   1.   4.   7.]]]


In [6]:
m1 = tf.constant([[1.],[0.],[-1.],[2.],[4.]])
m2 = tf.constant([[2.]])
a1 = tf.constant([[10.]])

In [7]:
p1 = tf.matmul(x_data, m1)
p2 = tf.matmul(p1, m2)
add1 = tf.add(p2, a1)
for x_val in x_vals:
    print(sess.run(add1, feed_dict={x_data: x_val}))

[[ 102.]
 [  66.]
 [  58.]]
[[ 114.]
 [  78.]
 [  70.]]


In [10]:
merge = tf.summary.merge_all()

writer = tf.summary.FileWriter('/tmp/v1', sess.graph)