In [1]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import os
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [2]:
sess = tf.Session()

In [4]:
x_shape = [1, 4, 4, 1]
x_val = np.random.uniform(size=x_shape)

In [13]:
print(x_val)

[[[[ 0.95048554]
   [ 0.03617097]
   [ 0.11790834]
   [ 0.50885578]]

  [[ 0.7812147 ]
   [ 0.23236315]
   [ 0.55094859]
   [ 0.70939093]]

  [[ 0.32947709]
   [ 0.36341602]
   [ 0.39748962]
   [ 0.73180794]]

  [[ 0.51245131]
   [ 0.9953309 ]
   [ 0.66064979]
   [ 0.14842686]]]]


In [5]:
x_data = tf.placeholder(tf.float32, shape=x_shape)

In [15]:
my_filter = tf.constant(0.25, shape=[2, 2, 1, 1])
'''Given an input tensor of shape `[batch, in_height, in_width, in_channels]`  
  and a filter / kernel tensor of shape  
  `[filter_height, filter_width, in_channels, out_channels]`, this op  
  performs the following:  '''
my_strides = [1, 2, 2, 1]
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides,
                            padding='SAME', name='m_a_l')

In [10]:
print(sess.run(my_filter))

[[[[ 0.25]]

  [[ 0.25]]]


 [[[ 0.25]]

  [[ 0.25]]]]


In [11]:
def cus_lay(mat):
    mat_squeezes = tf.squeeze(mat)
    A = tf.constant([[1., 2.], [-1., 3.]])
    b = tf.constant(1., shape=[2, 2])
    tmp1 = tf.matmul(A, mat_squeezes)
    tmp2 = tf.add(tmp1, b)
    return tf.nn.sigmoid(tmp2)

with tf.name_scope('cus_layer') as scope:
    cus_layer1 = cus_lay(mov_avg_layer)
    

In [12]:
print(sess.run(mov_avg_layer, feed_dict={x_data: x_val}))

[[[[ 0.50005859]
   [ 0.47177589]]

  [[ 0.55016887]
   [ 0.48459354]]]]


In [16]:
print(sess.run(cus_layer1, feed_dict={x_data: x_val}))

[[ 0.9308871   0.91989809]
 [ 0.89571065  0.87889475]]


In [17]:
merge = tf.summary.merge_all()
w = tf.summary.FileWriter('/tmp/0203', sess.graph)